name: Test

on: [push]

jobs:
  install_homebrew:
    runs-on: macos-latest
    steps:
      - name: Install Homebrew
        run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - name: Tap Repo
        run: brew tap mtslzr/marmaduke-chromium
      - name: Update Brew
        run: brew update
      - name: Install Cask
        run: brew cask install marmaduke-chromium
      - name: Uninstall Cask
        run: brew cask uninstall marmaduke-chromium
      - name: Install Cask (nosync)
        run: brew cask install marmaduke-chromium-nosync
      - name: Uninstall Cask (nosync)
        run: brew cask uninstall marmaduke-chromium-nosync
      - name: Install Cask (ungoogled)
        run: brew cask install marmaduke-chromium-ungoogled
