name: Test

on: [push]

jobs:
  install_homebrew:
    runs-on: macos-latest
    steps:
      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" 
      - name: Tap Repo
        run: brew tap mtslzr/marmaduke-chromium
      - name: Update Brew
        run: brew update
      - name: Install Cask
        run: brew install --cask marmaduke-chromium
      - name: Uninstall Cask
        run: brew uninstall --cask marmaduke-chromium
      - name: Install Cask (nosync)
        run: brew install --cask marmaduke-chromium-nosync
      - name: Uninstall Cask (nosync)
        run: brew uninstall --cask marmaduke-chromium-nosync
      - name: Install Cask (ungoogled)
        run: brew install --cask marmaduke-chromium-ungoogled
